services:
  web:
    build: .
    container_name: football-tracker
    command: sh -c "python manage.py migrate && gunicorn FootballStatsTrackerProject.wsgi:application -b 0.0.0.0:${PORT:-8000}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env