# Generated by Django 5.1.4 on 2024-12-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0002_player_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='joined_date',
        ),
    ]
