# Generated by Django 5.1.4 on 2024-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0003_remove_player_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='marketValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shirtNumber',
            field=models.IntegerField(null=True),
        ),
    ]
