# Generated by Django 5.1.4 on 2024-12-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0004_player_joined_date_player_marketvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
