# Generated by Django 5.1.4 on 2024-12-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_players', '0005_player_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='banner',
        ),
    ]
