name: Django CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    name: Build and Test Django Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test